<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6Wp8JJt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6Wp8JJt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6Wp8JJt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6Wp8JJt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6Wp8JJt\App_KernelDevDebugContainer([
    'container.build_hash' => '6Wp8JJt',
    'container.build_id' => '3c749b9b',
    'container.build_time' => 1672909194,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6Wp8JJt');
